/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ywauran.kotlin

class User(val name: String, val age: Int) {
    override fun toString(): String {
        return "User(name=$name, age=$age)"
    }
}

//Data Class
data class DataUser(val name: String, val age: Int) {
    fun intro() {
        println("Perkenalkan nama saya $name")
    }
}

fun main(args: Array<String>) {
    val user = User("Harke", 21)
    val dataUser = DataUser("Harke", 21)

    println(user)
    println(dataUser)

    val ( name, age ) = dataUser
    println("Perkenalkan nama saya $name")

    dataUser.intro()
}
